// flow-typed signature: 1743c577b03de9572287a9a662f40172
// flow-typed version: <<STUB>>/frame-debounce_v1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'frame-debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'frame-debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'frame-debounce/index' {
  declare module.exports: $Exports<'frame-debounce'>;
}
declare module 'frame-debounce/index.js' {
  declare module.exports: $Exports<'frame-debounce'>;
}
